modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/nekomario28/BuyClaimChunks/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name} (${claim_backend_name})"
displayURL="https://github.com/nekomario28/BuyClaimChunks"
logoFile="buyclaimchunks_continued.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="${claim_dependency_mod_id}"
type="required"
versionRange="${claim_dependency_range}"
ordering="AFTER"
side="BOTH"
